// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_hKBomdWNxaw2yLCB_ZRyKm7nIthH7o',
    appId: '1:719790006041:web:f9f7e993d696586d012f88',
    messagingSenderId: '719790006041',
    projectId: 'supporter-555f5',
    authDomain: 'supporter-555f5.firebaseapp.com',
    storageBucket: 'supporter-555f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyv8qBon0gc_eqdfurkXrvDFwqmQDqiM',
    appId: '1:719790006041:android:fa2a717c0eefed01012f88',
    messagingSenderId: '719790006041',
    projectId: 'supporter-555f5',
    storageBucket: 'supporter-555f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQz3SjegcYVXimE2oxH1SSCpkHHEx_kRM',
    appId: '1:719790006041:ios:b16ff11588de511f012f88',
    messagingSenderId: '719790006041',
    projectId: 'supporter-555f5',
    storageBucket: 'supporter-555f5.appspot.com',
    iosBundleId: 'com.example.supporterWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQz3SjegcYVXimE2oxH1SSCpkHHEx_kRM',
    appId: '1:719790006041:ios:067881843bbbb8fe012f88',
    messagingSenderId: '719790006041',
    projectId: 'supporter-555f5',
    storageBucket: 'supporter-555f5.appspot.com',
    iosBundleId: 'com.example.supporterWebsite.RunnerTests',
  );
}
